Allow running "puavo-pkg reconfigure-upgrade" with "--ignore-unconfigure-error" switch that ignores possible failure from old package unconfigure.
Use this when booting so we can upgrade (at boot time)
puavo-pkg packages that have buggy/failing unconfigure
scripts.

diff --git a/parts/pkg/puavo-pkg b/parts/pkg/puavo-pkg
--- a/parts/pkg/puavo-pkg
+++ b/parts/pkg/puavo-pkg
@@ -83,7 +83,9 @@ Commands:
   reconfigure PACKAGE            reconfigure installed PACKAGE
   reconfigure --all              reconfigure all installed packages
 
-  reconfigure-upgrade PKG DIR    reconfigure package from new directory
+  reconfigure-upgrade [--ignore-unconfigure-error] PKG DIR
+                                 reconfigure package from new directory
+                                 (optionally ignore old package unconfigure error)
 
   remove PACKAGE                 remove installed PACKAGE
   remove --all                   remove all installed packages
@@ -908,10 +910,11 @@ prepare_pkg_with_installer()
 }
 
 reconfigure_upgrade_pkg() {
-  local pkg_name pkg_dir pkg_id old_pkg_id
+  local ignore_unconfigure_error old_pkg_id pkg_name pkg_dir pkg_id
 
   pkg_name=$1
   pkg_dir=$2
+  ignore_unconfigure_error=$3
 
   pkg_id=$(get_pkg_id "$pkg_dir") || return 1
   old_pkg_id=$(get_installed_pkg_id "$pkg_name") || return 1
@@ -920,8 +923,11 @@ reconfigure_upgrade_pkg() {
     if ! unconfigure_pkg "$pkg_name"; then
       [ $? -eq "$SC_ERR_BUSY" ] && g_sc=${SC_ERR_BUSY}
       touch "${pkg_dir}/.upgrade_failed_due_to_old_pkg_unconfigure" || true
-      log_error "failed to unconfigure package '${pkg_name}'"
-      return 1
+      if [ "$ignore_unconfigure_error" != 'true' ]; then
+        log_error "failed to unconfigure package '${pkg_name}'"
+        return 1
+      fi
+      log_warning "failed to unconfigure package '${pkg_name}' (but ignoring)"
     fi
   fi
 
@@ -952,7 +958,7 @@ install_pkg_with_installer()
   pkg_id=$(get_pkg_id "$pkg_dir")                || return 1
   old_pkg_id=$(get_installed_pkg_id "$pkg_name") || return 1
 
-  reconfigure_upgrade_pkg "$pkg_name" "$pkg_dir" || return 1
+  reconfigure_upgrade_pkg "$pkg_name" "$pkg_dir" false || return 1
 
   touch "${pkg_dir}/.installed" || true
 
@@ -1004,7 +1010,7 @@ switch_to_system_pkg()
     for pkg_dir in ${g_puavo_pkg_readonly_rootdir}/packages/${pkg_name}/*; do
       test -d "$pkg_dir" || break
       log_info "found system version for ${pkg_name}, reconfiguring"
-      reconfigure_upgrade_pkg "$pkg_name" "$pkg_dir" || {
+      reconfigure_upgrade_pkg "$pkg_name" "$pkg_dir" false || {
         log_error "could not switch to image version for ${pkg_name}"
         return 1
       }
@@ -1309,8 +1315,13 @@ case "${command}" in
     fi
     ;;
   reconfigure-upgrade)
+    ignore_unconfigure_error=false
+    if [ "${1:-}" = '--ignore-unconfigure-error' ]; then
+      ignore_unconfigure_error=true
+      shift
+    fi
     assert_args_count -eq 2 "$@"
-    reconfigure_upgrade_pkg "$1" "$2"
+    reconfigure_upgrade_pkg "$1" "$2" "$ignore_unconfigure_error"
     ;;
   remove)
     assert_args_count -eq 1 "$@"
